## **# import numpy as np**

In [2]:
import numpy as np

Creating a Vector

In [3]:
row = np.array([1,2,3,4])
print(row)

[1 2 3 4]


In [6]:
column = np.array([[1],
                  [2],
                  [3],
                  [4]])
print(column)

[[1]
 [2]
 [3]
 [4]]


## **Creting Matrix (two dimensional array)**


In [7]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **Creting Sparse matrix**

In [10]:
from scipy import sparse
matrix = np.array([[0,0,0],
                   [0,0,1],
                   [3,0,1]])

In [11]:
sparse_matrix = sparse.csr_matrix(matrix)
print(sparse_matrix)

  (1, 2)	1
  (2, 0)	3
  (2, 2)	1


In [13]:
mat=np.array([[0,0,0,0,0,0,0,0],
              [0,1,0,0,0,0,0,0],
              [3,0,0,0,0,0,0,0]])
sparse_mat = sparse.csr_matrix(mat)
print(sparse_mat)

  (1, 1)	1
  (2, 0)	3


# **Selecting** **Element** 

In [17]:
M= np.array([1,2,3,4,5,6])
M[5]

6

In [18]:
M[0:3]

array([1, 2, 3])

In [21]:
M[:5]

array([1, 2, 3, 4, 5])

In [22]:
M[3:]

array([4, 5, 6])

In [19]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix[1,1]

5

In [20]:
matrix[0:1,1:3]

array([[2, 3]])

In [23]:
matrix[2:3,:]

array([[7, 8, 9]])

In [24]:
matrix[:,0:1]

array([[1],
       [4],
       [7]])

# **Describe The matrix**

> Use shape,size,ndim



In [26]:
matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [32]:
matrix.shape  #(Number 0f row and number of column)

(3, 4)

In [28]:
matrix.size  #(Row*Column)

12

In [29]:
matrix.ndim  #View number of dimension

2

In [30]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [31]:
m.ndim

3

# **Add any didgit in matrix**

In [33]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [34]:
matrix+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [35]:
matrix-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# **Finding the Maximum and Minimum Value in the matrix**

In [39]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
m=np.max(matrix)
print(m)

9


In [41]:
min=np.min(matrix)
print(min)

1


**Finding the minimum and maximum in column and row by using axis  **

In [43]:
np.max(matrix,axis=0) #finding the maximum in in column usnig axis=0

array([7, 8, 9])

In [44]:
np.min(matrix,axis=0)

array([1, 2, 3])

In [46]:
np.max(matrix,axis=1)  #findig the max value in the row by using axis=1

array([3, 6, 9])

In [47]:
np.min(matrix,axis=1)

array([1, 4, 7])

# **Calculating the Averege,Variance and Standard**

In [49]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [50]:
mean_matrix=np.mean(matrix)  #Find the mean 
print(mean_matrix)

5.0


In [53]:
standard_matrix = np.std(matrix) #Find the Standard Deviation
print(standard_matrix)

2.581988897471611


In [54]:
var_matrix=np.var(matrix)
var_matrix

6.666666666666667

**Find the mean value in the column and row**

In [55]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [56]:
np.mean(matrix,axis=0)

array([4., 5., 6.])

In [57]:
np.mean(matrix,axis=1)

array([2., 5., 8.])

# **Reshaping Arrays**

In [60]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])

In [65]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [67]:
matrix.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
matrix.reshape(-1,1) #Here is the one usefull argument is -1 means "As many needed column and row" 

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [73]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

# **Transporting a Matrix**

In [74]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [76]:
matrix.T  #this function is swaped the matrix element

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [78]:
m=np.array([[1,2,3,4,5,6,7,8]])
m.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# **Flattening a Matrix**
**you need to transform a matrix into a one dimension matrix**


In [79]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [80]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
three_dimension=np.array([[[1,2,3],
                           [4,5,6],
                           [7,8,9]]])

In [84]:
three_dimension.ndim

3

In [88]:
one=three_dimension.flatten()
one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
one.ndim

1

# **Finding the Rank of a Matrix**

In [90]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [95]:
np.linalg.matrix_rank(matrix)

2

In [96]:
three_dimension

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [97]:
np.linalg.matrix_rank(three_dimension)

array([2])

# **Calculating the Determinant**

In [98]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [100]:
np.linalg.det(matrix)

0.0

In [101]:
np.linalg.det(three_dimension)

array([0.])

# **Getting the Diagonal of a Matrix**

In [102]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])


In [104]:
matrix.diagonal()

array([1, 5, 9])

In [110]:
matrix.diagonal(offset=1) #Return diagonal one above the main diagonal

array([2, 6])

In [111]:
matrix.diagonal(offset=-1)  #Return diagonal one below the main diagonal

array([4, 8])

# **Calculating the Trace of a Matrix**

In [112]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])


In [114]:
matrix.trace()  #means calculating the diagonal of a matrix

15

In [115]:
m=np.array([[2,4,6],
            [7,8,9],
            [1,9,7]])

In [116]:
m.trace()

17

# **Finding the Eigenvalue and Eigenvectors**

In [117]:
matrix = np.array([[1,-1,2],
                   [1,1,6],
                   [3,8,9]])

In [118]:
eigenvalues,eigenvectors =np.linalg.eig(matrix)

In [119]:
eigenvalues

array([13.33584952,  0.88475897, -3.2206085 ])

In [120]:
eigenvectors

array([[-0.10854731, -0.96648374, -0.43414013],
       [-0.44191126,  0.20298526, -0.70116895],
       [-0.89046725,  0.15718192,  0.56558329]])

In [128]:
matrix1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])


In [129]:
eigenvlaues,eigenvectors = np.linalg.eig(matrix1)

In [130]:
eigenvalues

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [131]:
eigenvectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

# **Calculating the Dot Products**

In [132]:
vactor_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [133]:
np.dot(vactor_a,vector_b)

32

In [134]:
matrix1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [137]:
np.dot(matrix,matrix1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# **Adding and Subtracting Matrices**

In [138]:
matrix1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

matrix2 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [139]:
np.add(matrix1,matrix2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [140]:
np.subtract(matrix1,matrix2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

 **We can simply use the "+" and "-" for subtracting and adding**

In [141]:
matrix1+matrix2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [142]:
matrix1-matrix2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# **Multiplying Matrices**

In [143]:
m=np.array([[1,2],
            [3,4]])

n=np.array([[4,5],
            [6,7]])

In [144]:
np.dot(m,n)

array([[16, 19],
       [36, 43]])

**Another way to multiply matrices using "@" operator**




In [151]:
m@n

array([[16, 19],
       [36, 43]])

**If we want to do element-wise multiplication,we can use the  "*" operator**

In [148]:
m

array([[1, 2],
       [3, 4]])

In [149]:
n

array([[4, 5],
       [6, 7]])

In [150]:
m*n

array([[ 4, 10],
       [18, 28]])

# **Inverting a Matrix**

**You want to calculate the inverse of a square matrix**

In [154]:
m=np.array([[1, 2],
            [3, 4]])
m

array([[1, 2],
       [3, 4]])

In [155]:
np.linalg.inv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [156]:
n=np.array([[1,4],
            [2,5]])

In [157]:
np.linalg.inv(n)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

# **Genrating Random values**

In [159]:
np.random.randint(0,5,3)

array([4, 4, 2])

In [161]:
np.random.randint(1,9,6)

array([2, 7, 2, 8, 7, 3])

In [163]:
np.random.randint(1,11,9).reshape(3,3)

array([[4, 2, 3],
       [1, 8, 5],
       [3, 2, 3]])

In [166]:
np.random.randint(1,15,12).reshape(4,3)

array([[ 5,  8, 12],
       [14,  5,  8],
       [ 5, 11, 10],
       [ 1,  3, 11]])

In [169]:
np.random.seed(1)
np.random.randint(1,5,5)

array([2, 4, 1, 1, 4])

In [172]:
np.random.seed(1)
np.random.randint(1,9,6).reshape(2,3)

array([[6, 4, 5],
       [1, 8, 2]])

In [176]:
np.random.normal(1.0,2.0,10).reshape(2,5)

array([[-0.60434568,  0.10224438, -1.21187015, -2.3090309 , -3.72693721],
       [ 3.2706907 , -1.03402827,  2.27472363, -0.71981321,  4.54521526]])

In [177]:
np.random.normal(3,5,10).reshape(5,2)

array([[-2.55181527,  3.90607133],
       [ 5.82172433,  0.16744885],
       [ 6.64987798,  4.86496895],
       [ 5.66905456,  2.5401335 ],
       [12.56910194,  4.65398565]])